export const demoBatches = [
  {
    _id: "1",
    batchname: "Full Stack Development",
    classes: "12th",
    createdbyteacher: "John Doe",
    typee: "Paid",
    duration: "6 months",
    batchimageurl: "https://picsum.photos/400/200?random=1",
    demolink: "https://youtu.be/hKVnRe-T_qk",
    description: "Master MERN stack with real-world projects.",
    price: "4999",
    totalEnrolled: 120,
    totalSubjects: 8,
    orgid: { _id: "org1", organisationname: "CodeBridge Academy" },
    teacherlist: ["teacher1"],
    teacheremail: "johndoe@academy.com",
    adminemail: "admin@academy.com",
    likes: 250,
  },
  {
    _id: "2",
    batchname: "AI & Machine Learning",
    classes: "B.Tech 3rd Year",
    createdbyteacher: "Alice Smith",
    typee: "Paid",
    duration: "1 year",
    batchimageurl: "https://picsum.photos/400/200?random=2",
    demolink: "https://youtu.be/hKVnRe-T_qk",
    description: "Hands-on ML & AI using Python, TensorFlow, and PyTorch.",
    price: "7999",
    totalEnrolled: 95,
    totalSubjects: 10,
    orgid: { _id: "org2", organisationname: "AI Hub" },
    teacherlist: ["teacher2"],
    teacheremail: "alice@aihub.com",
    adminemail: "admin@aihub.com",
    likes: 180,
  },
  {
    _id: "3",
    batchname: "Data Science Bootcamp",
    classes: "College Students",
    createdbyteacher: "Robert Lee",
    typee: "Free",
    duration: "3 months",
    batchimageurl: "https://picsum.photos/400/200?random=3",
    demolink: "https://youtu.be/hKVnRe-T_qk",
    description: "Learn Data Analysis, SQL, and Visualization tools.",
    price: "0",
    totalEnrolled: 300,
    totalSubjects: 6,
    orgid: { _id: "org3", organisationname: "DataLab" },
    teacherlist: ["teacher3"],
    teacheremail: "robert@datalab.com",
    adminemail: "admin@datalab.com",
    likes: 500,
  },
  {
    _id: "4",
    batchname: "Cyber Security Fundamentals",
    classes: "12th",
    createdbyteacher: "Sophia Brown",
    typee: "Free",
    duration: "4 months",
    batchimageurl: "https://picsum.photos/400/200?random=4",
    demolink: "https://youtu.be/hKVnRe-T_qk",
    description: "Secure coding, networks, and ethical hacking basics.",
    price: "0",
    totalEnrolled: 150,
    totalSubjects: 5,
    orgid: { _id: "org4", organisationname: "CyberShield" },
    teacherlist: ["teacher4"],
    teacheremail: "sophia@cybershield.com",
    adminemail: "admin@cybershield.com",
    likes: 210,
  },
  {
    _id: "5",
    batchname: "Cloud Computing with AWS",
    classes: "Graduates",
    createdbyteacher: "David Miller",
    typee: "Paid",
    duration: "5 months",
    batchimageurl: "https://picsum.photos/400/200?random=5",
    demolink: "https://youtu.be/hKVnRe-T_qk",
    description: "AWS, Docker, Kubernetes, and real-world DevOps.",
    price: "5999",
    totalEnrolled: 80,
    totalSubjects: 7,
    orgid: { _id: "org5", organisationname: "CloudMasters" },
    teacherlist: ["teacher5"],
    teacheremail: "david@cloudmasters.com",
    adminemail: "admin@cloudmasters.com",
    likes: 160,
  },
  {
    _id: "6",
    batchname: "Competitive Programming",
    classes: "High School",
    createdbyteacher: "Emma Johnson",
    typee: "Free",
    duration: "2 months",
    batchimageurl: "https://picsum.photos/400/200?random=6",
    demolink: "https://youtu.be/hKVnRe-T_qk",
    description: "Master DSA and problem-solving for coding contests.",
    price: "0",
    totalEnrolled: 450,
    totalSubjects: 12,
    orgid: { _id: "org6", organisationname: "CP Warriors" },
    teacherlist: ["teacher6"],
    teacheremail: "emma@cpwarriors.com",
    adminemail: "admin@cpwarriors.com",
    likes: 600,
  },
  {
    _id: "7",
    batchname: "Blockchain Development",
    classes: "B.Tech Final Year",
    createdbyteacher: "Chris Evans",
    typee: "Paid",
    duration: "6 months",
    batchimageurl: "https://picsum.photos/400/200?random=7",
    demolink: "https://youtu.be/hKVnRe-T_qk",
    description: "Build DApps, smart contracts, and explore Web3.",
    price: "8999",
    totalEnrolled: 60,
    totalSubjects: 9,
    orgid: { _id: "org7", organisationname: "Web3 Builders" },
    teacherlist: ["teacher7"],
    teacheremail: "chris@web3builders.com",
    adminemail: "admin@web3builders.com",
    likes: 90,
  },
  {
    _id: "8",
    batchname: "UI/UX Design",
    classes: "Graduates",
    createdbyteacher: "Olivia Wilson",
    typee: "Paid",
    duration: "4 months",
    batchimageurl: "https://picsum.photos/400/200?random=8",
    demolink: "https://youtu.be/hKVnRe-T_qk",
    description: "Design beautiful, user-friendly apps and websites.",
    price: "3999",
    totalEnrolled: 140,
    totalSubjects: 6,
    orgid: { _id: "org8", organisationname: "DesignLab" },
    teacherlist: ["teacher8"],
    teacheremail: "olivia@designlab.com",
    adminemail: "admin@designlab.com",
    likes: 220,
  },
  {
    _id: "9",
    batchname: "Digital Marketing",
    classes: "College Students",
    createdbyteacher: "Liam Martinez",
    typee: "Free",
    duration: "3 months",
    batchimageurl: "https://picsum.photos/400/200?random=9",
    demolink: "https://youtu.be/hKVnRe-T_qk",
    description: "SEO, SEM, social media marketing, and growth hacking.",
    price: "0",
    totalEnrolled: 230,
    totalSubjects: 5,
    orgid: { _id: "org9", organisationname: "Growth Hackers" },
    teacherlist: ["teacher9"],
    teacheremail: "liam@growthhackers.com",
    adminemail: "admin@growthhackers.com",
    likes: 300,
  },
  {
    _id: "10",
    batchname: "Game Development",
    classes: "College Students",
    createdbyteacher: "Ava Taylor",
    typee: "Paid",
    duration: "8 months",
    batchimageurl: "https://picsum.photos/400/200?random=10",
    demolink: "https://youtu.be/hKVnRe-T_qk",
    description: "Unity, Unreal Engine, and multiplayer game design.",
    price: "6999",
    totalEnrolled: 110,
    totalSubjects: 10,
    orgid: { _id: "org10", organisationname: "GameVerse" },
    teacherlist: ["teacher10"],
    teacheremail: "ava@gameverse.com",
    adminemail: "admin@gameverse.com",
    likes: 175,
  },
];
